# Generated by Django 5.2.7 on 2025-10-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="annif_date",
            new_name="birth_date",
        ),
    ]
